[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
dominion-protector = { version = "0.1.0", path = "../dominion-protector" }
anyhow = { workspace = true, features = ["backtrace"] }
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.1"
clap.workspace = true
